### ISSUE TITLE
infografia

### ISSUE THREAD

**Issue by GerardoNR** [SistemasTecTlaxiaco/infografia-de-hilos-GerardoNR#2]
https://drive.google.com/file/d/1M0JykL7cjzDNpO9zDBpnOq7pi8l3knRl/view?usp=sharing

**Comment by ArcangelGC** [comment]
Recibo infografia. ✍🏼
En base a la rúbrica y a cómo debe de ser una infografia hacemos las siguientes observaciones.

Observaciones:

Posee una buena informacion, resumida y clara.
Faltó una conclusión tiene todo menos una conclusión de que son los hilos.
Nuevamente una infografia solo debe de ocupar una hoja no dos.

La calificación es de 18/20

**Comment by josealfredo79** [comment]
conclusion en una infografia......no lleva...bien hecho y revisado...
